# Generated by Django 5.2 on 2025-05-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('clave', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name_Prod', models.TextField(max_length=45, verbose_name='Nombre Producto')),
                ('Desc_Prod', models.TextField(max_length=45, verbose_name='Descripcion Producto')),
                ('PreV_Prod', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Producto')),
                ('Talla_Prod', models.TextField(max_length=5, verbose_name='Talla Producto')),
                ('Categoria', models.TextField(max_length=45, verbose_name='Categoria Producto')),
                ('Cost_Prom', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Costo Promocion (Si APLICA)')),
                ('Imagen', models.ImageField(null=True, upload_to='images/', verbose_name='Imagen')),
            ],
        ),
    ]
