# Generated by Django 5.2 on 2025-05-21 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False},
        ),
    ]
