# Generated by Django 5.2 on 2025-05-21 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slag', '0002_alter_producto_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='producto',
        ),
    ]
