# Generated by Django 5.2 on 2025-05-22 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slag', '0003_alter_producto_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
