# Generated by Django 5.2 on 2025-05-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slag', '0004_alter_usuario_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_cate', models.AutoField(primary_key=True, serialize=False)),
                ('Nom_Cate', models.TextField(max_length=45)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
    ]
