# Generated by Django 5.2 on 2025-06-14 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slag', '0005_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slag.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Tallas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('talla', models.CharField(max_length=5, verbose_name='Talla del producto')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad producto:')),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.CASCADE, to='slag.producto', verbose_name='ID del producto')),
            ],
            options={
                'db_table': 'tallas',
            },
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='slag.carrito')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slag.producto')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slag.tallas', verbose_name='')),
            ],
        ),
    ]
