# Generated by Django 5.2 on 2025-05-31 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slag', '0005_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tallas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('talla', models.CharField(max_length=5, verbose_name='Talla del producto')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad Producto:')),
            ],
            options={
                'db_table': 'tallas',
                'managed': False,
            },
        ),
    ]
