# Generated by Django 5.2.3 on 2025-06-27 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slag', '0006_carrito_tallas_itemcarrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(db_column='Id_Pedi', primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField(db_column='Date_Pedi')),
                ('fecha_entrega', models.CharField(db_column='Date_ent', max_length=45)),
                ('cliente', models.ForeignKey(db_column='Cliente_Id_Cliente', on_delete=django.db.models.deletion.CASCADE, to='slag.usuario')),
            ],
            options={
                'db_table': 'Pedido',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slag.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='slag.pedido')),
            ],
            options={
                'db_table': 'DetallePedido',
            },
        ),
    ]
