# Generated by Django 5.2 on 2025-06-06 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slag', '0006_tallas'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarroBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slag.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('acumulado', models.PositiveIntegerField(default=0)),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to='slag.Producto')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to='slag.Usuario')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to='slag.CarroBase')),
            ],
            options={
                'db_table': 'carro_producto',
            },
        ),
    ]

