# Generated by Django 5.2.3 on 2025-06-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slag', '0007_pedido_detallepedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formas_Envio',
            fields=[
                ('ide_Fore', models.IntegerField(db_column='Ide_Fore', max_length=11, primary_key=True, serialize=False)),
                ('nom_Fore', models.CharField(db_column='Nom_Fore', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_Pago', models.IntegerField(db_column='Id_Pago', max_length=11, primary_key=True, serialize=False)),
                ('nom_metpa', models.CharField(db_column='nom_metpa', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Transportadora',
            fields=[
                ('ide_Trans', models.IntegerField(db_column='Ide_Trans', max_length=11, primary_key=True, serialize=False)),
                ('nom_Trans', models.CharField(db_column='Nom_Trans', max_length=45)),
                ('Tel_Trans', models.CharField(db_column='Tel_Trans', max_length=45)),
                ('Dir_Trans', models.CharField(db_column='Dir_Trans', max_length=45)),
            ],
        ),
        migrations.AlterModelOptions(
            name='detallepedido',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tallas',
            options={'managed': False},
        ),
    ]
