# Generated by Django 5.2.3 on 2025-07-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slag', '0008_formas_envio_pago_transportadora_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioViejo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre Usuario')),
                ('email', models.CharField(max_length=45, verbose_name='Email Usuario')),
                ('telefono', models.CharField(max_length=20, verbose_name='Numero Telefono Usuario')),
                ('direccion', models.TextField(max_length=45, verbose_name='Direccion Residencia Usuario')),
                ('FechaNa', models.DateField(verbose_name='Fecha Nacimiento CLiente')),
                ('clave', models.CharField(max_length=45, verbose_name='Contraseña Usuario')),
            ],
        ),
    ]
