# Generated by Django 5.2.3 on 2025-07-01 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slag', '0009_usuarioviejo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarioviejo',
            options={'managed': False},
        ),
    ]
