# Generated by Django 5.2.3 on 2025-07-01 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slag', '0010_alter_usuarioviejo_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuarioviejo',
            table='usuario',
        ),
    ]
