# Generated by Django 5.2.3 on 2025-07-01 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slag', '0011_alter_usuarioviejo_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioViejo',
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
    ]
