# Generated by Django 5.2.3 on 2025-07-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('slag', '0012_delete_usuarioviejo_alter_usuario_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='clave',
        ),
        migrations.AddField(
            model_name='usuario',
            name='FechaNa',
            field=models.DateField(default='1990-01-01', verbose_name='Fecha Nacimiento CLiente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.TextField(default='Sin dirección', max_length=45, verbose_name='Direccion Residencia Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$J7EpK8V9VE9ONAgRtw9bV1$L7jC3Z7bn3ld5EIXW9ex5w9C3oZFnPE9QgD+oyNoWlY=', max_length=45, verbose_name='Contraseña Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default='0000000000', max_length=20, verbose_name='Numero Telefono Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=45, unique=True, verbose_name='Nombre Usuario'),
        ),
    ]
