# Generated by Django 5.2.3 on 2025-07-01 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slag', '0013_remove_usuario_clave_usuario_fechana_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrito',
            options={'managed': False},
        ),
    ]
