# Generated by Django 5.2.3 on 2025-07-01 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slag', '0014_alter_carrito_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='carrito',
            table='slag_carrito',
        ),
    ]
