# Generated by Django 5.2.3 on 2025-07-02 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slag', '0015_alter_usuario_options_alter_carrito_table'),
    ]

    operations = [
    ]
