# Generated by Django 5.2.3 on 2025-07-04 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slag', '0016_auto_20250702_0105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transportadora',
            options={'managed': False},
        ),
    ]
