# Generated by Django 5.2.3 on 2025-07-04 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slag', '0017_alter_transportadora_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formas_envio',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='transportadora',
            table='transportadora',
        ),
    ]
