# Generated by Django 5.2.3 on 2025-07-04 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slag', '0018_alter_formas_envio_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='formas_envio',
            table='formas_envio',
        ),
    ]
